### ISSUE TITLE
jobsprojenv directory: no need to commit to github

### ISSUE THREAD

**Issue by shadiakiki1986** [minerva22/ffa-jobs-emails#1]
I noticed that you committed a folder called "jobsprojenv" to the repository.
This repository is created automatically when you run `pip install` after running `virtualenv`,
so it doesn't need to be committed.
It also makes your repository size bigger than necessary. For example, the `ffa-blotter` repository is 137 kB, whereas your repository is larger than 5 MB.
That makes the `git clone` take a lot of time.
Better to remove it from the repository (keep it in your local disk, and add it to `.gitignore`)

**Comment by minerva22** [comment]
done
