### ISSUE TITLE
redirect "/" to "/emailffa"

### ISSUE THREAD

**Issue by shadiakiki1986** [minerva22/ffa-jobs-emails#7]
This will avoid getting the error "Page not found" when opening "pmo.ffaprivatebank.com:8004"

**Comment by minerva22** [comment]
modify the url pattern to be url(r'^', include('emailffa.urls'))

**Comment by shadiakiki1986** [comment]
Check [comment](https://github.com/minerva22/ffa-jobs-emails/commit/02de0bd4768db112d269fdd769cc0d73921491e7#commitcomment-23175613)
