### ISSUE TITLE
Add link to github repository

### ISSUE THREAD

**Issue by shadiakiki1986** [minerva22/ffa-jobs-emails#9]
i.e. 
https://github.com/minerva22/ffa-jobs-emails/

at the bottom of the pages

**Comment by shadiakiki1986** [comment]
How is this closed? I did a git pull and runserver and still don't see a link

**Comment by minerva22** [comment]
I closed it before publishing, please try now

**Comment by shadiakiki1986** [comment]
possible duplicate of #21
